/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.telescope": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "current-user.destroy": [],
    "api-tokens.index": [],
    "api-tokens.store": [],
    "api-tokens.update": [
        {
            "name": "token",
            "required": true
        }
    ],
    "api-tokens.destroy": [
        {
            "name": "token",
            "required": true
        }
    ],
    "teams.create": [],
    "teams.store": [],
    "teams.show": [
        {
            "name": "team",
            "required": true
        }
    ],
    "teams.update": [
        {
            "name": "team",
            "required": true
        }
    ],
    "teams.destroy": [
        {
            "name": "team",
            "required": true
        }
    ],
    "current-team.update": [],
    "team-members.store": [
        {
            "name": "team",
            "required": true
        }
    ],
    "team-members.update": [
        {
            "name": "team",
            "required": true
        },
        {
            "name": "user",
            "required": true
        }
    ],
    "team-members.destroy": [
        {
            "name": "team",
            "required": true
        },
        {
            "name": "user",
            "required": true
        }
    ],
    "team-invitations.accept": [
        {
            "name": "invitation",
            "required": true
        }
    ],
    "team-invitations.destroy": [
        {
            "name": "invitation",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "welcome": [],
    "dashboard": [],
    "web.clubs.index": [],
    "web.clubs.create": [],
    "web.clubs.store": [],
    "web.clubs.show": [
        {
            "name": "club",
            "required": true,
            "binding": "id"
        }
    ],
    "web.clubs.edit": [
        {
            "name": "club",
            "required": true,
            "binding": "id"
        }
    ],
    "web.clubs.update": [
        {
            "name": "club",
            "required": true,
            "binding": "id"
        }
    ],
    "web.clubs.patch": [
        {
            "name": "club",
            "required": true,
            "binding": "id"
        }
    ],
    "web.clubs.destroy": [
        {
            "name": "club",
            "required": true,
            "binding": "id"
        }
    ],
    "web.teams.index": [],
    "web.teams.create": [],
    "web.teams.store": [],
    "web.teams.show": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "web.teams.edit": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "web.teams.update": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "web.teams.patch": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "web.teams.destroy": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "web.teams.players.index": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "web.teams.players.attach": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "web.teams.players.update": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "player",
            "required": true
        }
    ],
    "web.teams.players.detach": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "player",
            "required": true
        }
    ],
    "players.search": [],
    "test.teams.create": [],
    "web.players.index": [],
    "web.players.create": [],
    "web.players.store": [],
    "web.players.show": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "web.players.edit": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "web.players.update": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "web.players.patch": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "web.players.destroy": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "web.games.index": [],
    "web.games.create": [],
    "web.games.store": [],
    "web.games.show": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "web.games.edit": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "web.games.update": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "web.games.patch": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "web.games.destroy": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "training.index": [],
    "training.sessions": [],
    "training.drills": [],
    "training.sessions.show": [
        {
            "name": "session",
            "required": true,
            "binding": "id"
        }
    ],
    "statistics.index": [],
    "statistics.teams": [],
    "statistics.players": [],
    "statistics.games": [],
    "games.live-scoring": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.start": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.finish": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.add-action": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.update-score": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.control-clock": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.timeout": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.end-timeout": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.substitution": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.reset-shot-clock": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.update-players-on-court": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.correct-action": [
        {
            "name": "action",
            "required": true,
            "binding": "id"
        }
    ],
    "games.delete-action": [
        {
            "name": "action",
            "required": true,
            "binding": "id"
        }
    ],
    "games.live-data": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.statistics": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.settings": [],
    "admin.settings.update": [],
    "admin.users": [],
    "admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.system": [],
    "export.game-stats-pdf": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "export.game-stats-excel": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "export.game-scoresheet": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "export.player-stats-pdf": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "export.player-stats-excel": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "export.team-stats-pdf": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "export.team-stats-excel": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "export.shot-chart-csv": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        },
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "export.league-standings-pdf": [],
    "subscription.index": [],
    "subscription.config": [],
    "subscription.checkout": [],
    "subscription.success": [],
    "subscription.cancel": [],
    "subscription.cancel-subscription": [],
    "subscription.resume": [],
    "subscription.swap": [],
    "subscription.update-payment-method": [],
    "subscription.invoices": [],
    "subscription.invoice": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "de.welcome": [],
    "de.dashboard": [],
    "en.welcome": [],
    "en.dashboard": [],
    "checkout.subscription": [],
    "checkout.subscription.session": [],
    "checkout.subscription.success": [],
    "checkout.subscription.cancel": [],
    "checkout.payment-methods": [],
    "checkout.payment-methods.session": [],
    "checkout.payment-methods.success": [],
    "checkout.payment-methods.remove": [
        {
            "name": "payment_method",
            "required": true
        }
    ],
    "checkout.payment-methods.default": [
        {
            "name": "payment_method",
            "required": true
        }
    ],
    "pricing": [],
    "demo": [],
    "webhooks.stripe": [],
    "webhooks.health": [],
    "federation.dbb.player.get": [],
    "federation.dbb.player.validate": [],
    "federation.dbb.player.transfer-status": [],
    "federation.dbb.leagues.index": [],
    "federation.dbb.team.register": [],
    "federation.dbb.game.submit-result": [],
    "federation.dbb.referees.assignments": [],
    "federation.dbb.status": [],
    "federation.dbb.test-connection": [],
    "federation.fiba.player.profile": [],
    "federation.fiba.player.search": [],
    "federation.fiba.player.eligibility": [],
    "federation.fiba.competitions.index": [],
    "federation.fiba.competitions.standings": [
        {
            "name": "competition_id",
            "required": true
        }
    ],
    "federation.fiba.club.info": [],
    "federation.fiba.team.register-competition": [],
    "federation.fiba.game.official-data": [],
    "federation.fiba.referee.info": [],
    "federation.fiba.status": [],
    "federation.fiba.test-connection": [],
    "federation.webhooks.dbb.player-update": [],
    "federation.webhooks.dbb.team-status": [],
    "federation.webhooks.dbb.game-schedule": [],
    "pwa.service-worker": [],
    "pwa.manifest": [],
    "pwa.offline": [],
    "service-worker": [],
    "manifest": [],
    "offline": [],
    "pwa.status": [],
    "pwa.clear-caches": [],
    "pwa.update-service-worker": [],
    "pwa.queue-offline-data": [],
    "pwa.process-offline-queue": [
        {
            "name": "type",
            "required": true
        }
    ],
    "pwa.subscribe-push": [],
    "api.sync.game-stats": [],
    "api.sync.player-data": [],
    "api.sync.training-data": [],
    "federation.sync.dbb": [],
    "federation.sync.fiba": [],
    "pwa.install.check": [],
    "pwa.install.instructions": [],
    "emergency.pwa.manifest": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.pwa.service-worker": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.pwa.install": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.pwa.offline": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.pwa.cache": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "api.emergency.create-incident": [],
    "api.emergency.log-contact-access": [],
    "notifications.push.subscriptions.index": [],
    "notifications.push.subscriptions.delete": [
        {
            "name": "subscription",
            "required": true
        }
    ],
    "notifications.push.test": [],
    "notifications.push.game.start": [],
    "notifications.push.game.score-update": [],
    "notifications.push.player.foul": [],
    "notifications.push.training.reminder": [],
    "notifications.push.emergency": [],
    "notifications.push.federation.sync": [],
    "notifications.push.custom": [],
    "notifications.push.stats": [],
    "notifications.push.config": [],
    "notifications.push.cleanup": [],
    "webhooks.push.delivery-status": [],
    "webhooks.push.subscription-change": [],
    "events.game.started": [
        {
            "name": "game",
            "required": true
        }
    ],
    "events.game.score-changed": [
        {
            "name": "game",
            "required": true
        }
    ],
    "events.player.foul": [
        {
            "name": "player",
            "required": true
        }
    ],
    "events.training.reminder": [
        {
            "name": "training",
            "required": true
        }
    ],
    "events.federation.synced": [
        {
            "name": "type",
            "required": true
        }
    ],
    "notifications.scheduled.game-reminders": [],
    "notifications.scheduled.training-series": [],
    "emergency.health": [],
    "emergency.access.form": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.access.process": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.access.direct": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.access.printable": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.api.offline.data": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.api.player.contacts": [
        {
            "name": "accessKey",
            "required": true
        },
        {
            "name": "playerId",
            "required": true
        }
    ],
    "emergency.api.record.call": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "emergency.api.report.incident": [
        {
            "name": "accessKey",
            "required": true
        }
    ],
    "api.v2.emergency.contacts.index": [],
    "api.v2.emergency.contacts.store": [],
    "api.v2.emergency.contacts.show": [
        {
            "name": "contact",
            "required": true
        }
    ],
    "api.v2.emergency.contacts.update": [
        {
            "name": "contact",
            "required": true
        }
    ],
    "api.v2.emergency.contacts.destroy": [
        {
            "name": "contact",
            "required": true
        }
    ],
    "api.v2.emergency.contacts.by-player": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.emergency.contacts.set-primary": [
        {
            "name": "emergencyContact",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.emergency.contacts.update-consent": [
        {
            "name": "emergencyContact",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.emergency.contacts.generate-qr": [
        {
            "name": "emergencyContact",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.emergency.legacy.access": [
        {
            "name": "token",
            "required": true
        }
    ],
    "api.v2.emergency.statistics": [],
    "admin.emergency.access.index": [],
    "admin.emergency.access.store": [],
    "admin.emergency.access.show": [
        {
            "name": "access",
            "required": true
        }
    ],
    "admin.emergency.access.update": [
        {
            "name": "access",
            "required": true
        }
    ],
    "admin.emergency.access.destroy": [
        {
            "name": "access",
            "required": true
        }
    ],
    "admin.emergency.access.regenerate-qr": [
        {
            "name": "access",
            "required": true
        }
    ],
    "admin.emergency.access.bulk-create": [],
    "admin.emergency.access.bulk-deactivate": [],
    "admin.emergency.incidents.index": [],
    "admin.emergency.incidents.show": [
        {
            "name": "incident",
            "required": true
        }
    ],
    "admin.emergency.incidents.update": [
        {
            "name": "incident",
            "required": true
        }
    ],
    "admin.emergency.incidents.resolve": [
        {
            "name": "incident",
            "required": true
        }
    ],
    "admin.emergency.analytics.dashboard": [],
    "admin.emergency.analytics.usage": [],
    "admin.emergency.analytics.incidents": [],
    "admin.emergency.analytics.export": [],
    "webhooks.emergency.notification": [],
    "webhooks.emergency.sms-status": [],
    "webhooks.emergency.call-status": [],
    "emergency.service-worker": [],
    "emergency.manifest": [],
    "gdpr.public.request.form": [],
    "gdpr.public.request.submit": [],
    "gdpr.admin.dashboard": [],
    "gdpr.admin.requests.index": [],
    "gdpr.admin.requests.show": [
        {
            "name": "request",
            "required": true,
            "binding": "id"
        }
    ],
    "gdpr.admin.requests.process": [
        {
            "name": "request",
            "required": true
        }
    ],
    "gdpr.admin.requests.verify-identity": [
        {
            "name": "request",
            "required": true
        }
    ],
    "gdpr.admin.requests.download-export": [
        {
            "name": "request",
            "required": true
        }
    ],
    "gdpr.admin.consents.index": [],
    "gdpr.admin.consents.bulk-renewal": [],
    "gdpr.admin.processing-records": [],
    "gdpr.admin.generate-report": [],
    "data-subject.dashboard": [],
    "data-subject.consents": [],
    "data-subject.consents.update": [],
    "data-subject.requests": [],
    "data-subject.requests.create": [],
    "data-subject.requests.store": [],
    "data-subject.requests.show": [
        {
            "name": "request",
            "required": true,
            "binding": "id"
        }
    ],
    "data-subject.requests.download": [
        {
            "name": "request",
            "required": true
        }
    ],
    "data-subject.privacy-settings": [],
    "api.gdpr.consents.mine": [],
    "api.gdpr.consents.update": [],
    "api.gdpr.export": [],
    "webhooks.gdpr.consent-update": [],
    "webhooks.gdpr.erasure-confirmation": [],
    "gdpr.health": [],
    "api.v1.teams.index": [],
    "api.v1.teams.store": [],
    "api.v1.teams.show": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.v1.teams.update": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "players.index": [],
    "players.store": [],
    "players.show": [
        {
            "name": "player",
            "required": true
        }
    ],
    "players.update": [
        {
            "name": "player",
            "required": true
        }
    ],
    "games.index": [],
    "games.store": [],
    "games.show": [
        {
            "name": "game",
            "required": true
        }
    ],
    "games.update": [
        {
            "name": "game",
            "required": true
        }
    ],
    "users.index": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.clubs.index": [],
    "api.v2.clubs.store": [],
    "api.v2.clubs.show": [
        {
            "name": "club",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.clubs.update": [
        {
            "name": "club",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.clubs.destroy": [
        {
            "name": "club",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.teams.index": [],
    "api.v2.teams.store": [],
    "api.v2.teams.show": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.v2.teams.update": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.v2.teams.destroy": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.v2.players.index": [],
    "api.v2.players.store": [],
    "api.v2.players.show": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.players.update": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.players.destroy": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "api.games.shot-chart": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "api.games.heat-map": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "api.players.shot-chart": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "api.players.heat-map": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "api.players.shooting-zones": [
        {
            "name": "player",
            "required": true,
            "binding": "id"
        }
    ],
    "api.teams.shot-chart": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.teams.heat-map": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.teams.shooting-analysis": [
        {
            "name": "team",
            "required": true,
            "binding": "slug"
        }
    ],
    "emergency-contacts.index": [],
    "emergency-contacts.store": [],
    "emergency-contacts.show": [
        {
            "name": "emergency_contact",
            "required": true
        }
    ],
    "emergency-contacts.update": [
        {
            "name": "emergency_contact",
            "required": true
        }
    ],
    "emergency-contacts.destroy": [
        {
            "name": "emergency_contact",
            "required": true
        }
    ],
    "api.analytics.": [
        {
            "name": "player",
            "required": true
        }
    ],
    "api.live.": [
        {
            "name": "player",
            "required": true
        }
    ],
    "api.public.": [
        {
            "name": "player",
            "required": true
        }
    ],
    "api.export.": [
        {
            "name": "model",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v4.teams.index": [],
    "api.v4.teams.store": [],
    "api.v4.teams.show": [
        {
            "name": "team",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v4.teams.update": [
        {
            "name": "team",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v4.teams.destroy": [
        {
            "name": "team",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
