<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Add analytics helper fields to clubs table for faster queries and reporting.
     * These denormalized fields improve performance for common analytics queries.
     */
    public function up(): void
    {
        Schema::table('clubs', function (Blueprint $table) {
            // Revenue tracking
            $table->decimal('lifetime_revenue', 10, 2)->default(0)->after('payment_method_id')
                ->comment('Total revenue generated by this club across all time');

            // Billing tracking
            $table->date('last_billing_date')->nullable()->after('lifetime_revenue')
                ->comment('Date of last successful payment');

            // Current MRR (denormalized for quick access)
            $table->decimal('mrr', 8, 2)->default(0)->after('last_billing_date')
                ->comment('Current monthly recurring revenue (normalized from billing interval)');

            // Indexes for analytics queries
            $table->index('mrr', 'idx_clubs_mrr');
            $table->index('last_billing_date', 'idx_clubs_last_billing');
            $table->index(['tenant_id', 'subscription_status'], 'idx_clubs_tenant_status');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('clubs', function (Blueprint $table) {
            // Drop indexes first
            $table->dropIndex('idx_clubs_mrr');
            $table->dropIndex('idx_clubs_last_billing');
            $table->dropIndex('idx_clubs_tenant_status');

            // Drop columns
            $table->dropColumn([
                'lifetime_revenue',
                'last_billing_date',
                'mrr',
            ]);
        });
    }
};
