<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Create club_subscription_cohorts table for pre-computed cohort analysis.
     * Cohorts group clubs that started their subscription in the same month,
     * enabling retention and LTV tracking over time.
     */
    public function up(): void
    {
        Schema::create('club_subscription_cohorts', function (Blueprint $table) {
            $table->id();
            $table->char('tenant_id', 36);
            $table->date('cohort_month')->comment('First day of cohort month (YYYY-MM-01)');

            // Cohort size
            $table->integer('cohort_size')->default(0)->comment('Number of clubs that started subscription in this month');

            // Retention rates by month (percentage of cohort still active)
            $table->decimal('retention_month_1', 5, 2)->default(100.00)->comment('% still active after 1 month');
            $table->decimal('retention_month_2', 5, 2)->default(0)->comment('% still active after 2 months');
            $table->decimal('retention_month_3', 5, 2)->default(0)->comment('% still active after 3 months');
            $table->decimal('retention_month_6', 5, 2)->default(0)->comment('% still active after 6 months');
            $table->decimal('retention_month_12', 5, 2)->default(0)->comment('% still active after 12 months');

            // Revenue metrics
            $table->decimal('cumulative_revenue', 10, 2)->default(0)->comment('Total revenue generated by this cohort');
            $table->decimal('avg_ltv', 10, 2)->default(0)->comment('Average lifetime value per club in cohort');

            // Calculation tracking
            $table->timestamp('last_calculated_at')->nullable();
            $table->timestamps();

            // Unique constraint and indexes
            $table->unique(['tenant_id', 'cohort_month']);
            $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();
            $table->index('cohort_month');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('club_subscription_cohorts');
    }
};
